name: mobile_app
description: IoT Classroom Mobile App
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^13.2.0
  mqtt_client: ^10.0.0
  web_socket_channel: ^3.0.0
  fl_chart: ^0.66.0
  flutter_local_notifications: 15.1.2
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  logger: ^2.0.2
  uuid: ^4.2.2
  path_provider: ^2.1.1
  meta: ^1.16.0
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_local_notifications:
    path: C:\Users\TUYEN\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_local_notifications-15.1.2